### ISSUE TITLE
Volume control not working (Onkyo TX-NR555)

### ISSUE THREAD

**Issue by dsieber** [phillyfan1138/onkyo-yatse-plugin#7]
Got the Update to Yatse 7.5.5 and read about this plugin in the changelog. Added it to my Kodi host in the Yatse settings and was able to successfully control volume from the test screen. When playing a movie I still cannot control the volume using Yatse though. Is there anything I've missed?

**Comment by Xhinde** [comment]
Same issue here. Tested with music playing too. TX-NR636

**Comment by danielhstahl** [comment]
Thanks for submitting the issue!  I have a couple ideas on what might be going on...first [neither receiver is on the list of compatible receivers](https://github.com/phillyfan1138/onkyo-yatse-plugin/blob/master/README.md) but that is a minor point since I don't think Onkyo has changed their codes.  

Would it be possible for one of you to upload a log?  The description of how to do so is at https://yatse.tv/redmine/projects/yatse/knowledgebase/articles/20.  

I'll create a branch to try to resolve this...would either of you be willing to download an APK directly from the github repository?  You may have to uninstall your current plugin to do so.

**Comment by Xhinde** [comment]
I'd be willing to try it. 
https://pastebin.com/upcxxMr1

**Comment by dsieber** [comment]
I can try the APK when I'm back home later. Log created while trying to change volume http://sprunge.us/fDJd

**Comment by danielhstahl** [comment]
Thanks both of you!  I've uploaded a new apk at https://github.com/phillyfan1138/onkyo-yatse-plugin/blob/master/sample/sample-release.apk.  Let me know if that works better for you!

**Comment by sipaan** [comment]
Can't find my 636 during setup. Even entering the IP manually did not help. Not supported?

**Comment by danielhstahl** [comment]
@sipaan Xhinde doesn't seem to have that issue so I'm guessing that its something to do with your specific setup; not the receiver.  Is the receiver on?  Is the receiver connected to your local network?  Is the port the default (60128)?  Some receiver's may only work over ethernet.

**Comment by Xhinde** [comment]
@phillyfan1138 works now, at least here. Thanks. To help sipaan. Yes i have a wired connection and a static IP for the AVR.

**Comment by danielhstahl** [comment]
@Xhinde Excellent!  @Tolriq Is this something we can update to the play store easily?

**Comment by Tolriq** [comment]
@phillyfan1138 pushed + PR ;)

**Comment by danielhstahl** [comment]
Merged!

**Comment by dsieber** [comment]
@phillyfan1138 @Tolriq thanks a bunch to the both of you! Just updated the addon from the play store and it's working now with my AVR after reselecting it in the host's settings 👍.
