### ISSUE TITLE
Plugin prevents official Onkyo app to connect

### ISSUE THREAD

**Issue by protobock** [phillyfan1138/onkyo-yatse-plugin#9]
The plugin works correctly on my TX-NR1030 but it prevents the "official Onkyo Remote" app from connecting to the receiver. The Onkyo app tries to connect and when it seems to have connected it tries to connect again. Endlessly.

**Comment by danielhstahl** [comment]
I'm guessing this is due to the perpetual loop to the receiver.  I'll try to replicate this at home.  I'm thinking of adding an option to turn off the loop.  When the loop is turned off changes to the receiver from sources outside the Yatse app will not be registered (eg, the mute button won't toggle on the app when muting from a different remote).

**Comment by danielhstahl** [comment]
I just tested this and both work fine on my phone and receiver combination.  

Would you be interested in an option to turn off communication from the receiver?  Doing so would break communication between the receiver and Yatse.  Yatse to receiver communication would still work fine.

**Comment by protobock** [comment]
Thank you for your very quick reply!
Yes I would be really interested by such an option.
Your plugin (particularly the ability to perform custom commands) is awesome but the issue I mentioned prevents me from using it at the moment.

**Comment by danielhstahl** [comment]
Well since I don't have the issue I cant promise that the option will help you out but I've added it.  @Tolriq for some reason Android Studio is telling me "Default Activity" isn't found even though I didn't change any settings.  When I generate the APK I can't update it the plugin either; so I can't test the functionality.

**Comment by Tolriq** [comment]
@phillyfan1138 
Yes it's normal as there's no default activity now as it should not be.

You need to configure in edit configuration and select none as activity to launch.

About updating from Play Store with APK you sign, I did warn you when I asked you about signing that this won't be possible and a problem for you and users but preferred to go that way. You need to uninstall the Play Store version before installing your APK.

**Comment by danielhstahl** [comment]
@ Tolriq Yeah I'm just surprised it took so long...I'd been using the same config for a while without issues after your changes.  

@protobock The signed APK available in this repo (not on the play store yet) now features a checkbox to disable retrieval of information from the receiver.  Let me know if this works for you!

**Comment by protobock** [comment]
I had not much time to test it carefully but it seems to work like a charm! 
Thank you very much!

**Comment by danielhstahl** [comment]
Awesome!  Glad it works! @Tolriq , I think I've updated versions and made sure that its ready for the play store.

**Comment by Tolriq** [comment]
@phillyfan1138 push to Play Store + a PR to update the correct field for release ;)

You may want to use ctrl+alt+L in AS for automatic code formatting, even if you do not have your own standard this helps to have better code.

**Comment by danielhstahl** [comment]
Merged!
